### ISSUE TITLE
Device - cast - support

### ISSUE THREAD

**Issue by Gecrator996** [SwagLyrics/SwSpotify#11]
**Preconditions:**
Swag-lyrics turned on - currently playing.
 - Alexa Echo bot.

**To Reproduce**
1. Click on "Devices Available"
2. Click on "Connected device" 
3. See error

**Expected behavior**
Lyrics showed up. 

**Actual result:**
<
   Nothing Playing.
   Lyrics unavailable for by .
>

**Comment by aadibajpai** [comment]
https://community.spotify.com/t5/Desktop-Windows/BUG-Window-title-is-not-set-to-the-currently-playing-song-if/m-p/4869439#M82257 escalated to Spotify

**Comment by aadibajpai** [comment]
Resolving #10 will also resolve this because then you could simply just open it on chrome as well while the music is playing on your Alexa or Google Home or any other cast device

**Comment by aadibajpai** [comment]
Fixed! You can use the Spotify Web Player with the Chrome Extensionhttps://chrome.google.com/webstore/detail/swaglyrics-for-spotify/miopldoofdhmipepmnclnoangcdffmlk and the song playing from the cast device will show up.

Tested it myself, let me know if this works for you :)
