### ISSUE TITLE
[BUG] Doesn't work

### ISSUE THREAD

**Issue by bartekpacia** [SwagLyrics/SwSpotify#21]
**Describe the bug**
Was working fine. I updated Spotify app a few times, doesn't work anymore 

**To Reproduce**
1. Play any song on newest Spotify app on mac
2. `swaglyrics -c` 
3. Doesn't detect artist and song name (even Despacito doesn't work)

```
$ swaglyrics -c
Updating unsupported.txt from server.
Updated unsupported.txt successfully.
Lyrics unavailable for  by .


(Press Ctrl+C to quit)
^C
Sure boss, exiting.
```

**Expected behavior**
should work

**Desktop (please complete the following information):**
- MacOS 10.15.4
 - swaglyrics: 1.1.2
 - Spotify app version:  1.1.31.703.g256add22

**Comment by aadibajpai** [comment]
Ok this is actually a SwSpotify issue (even though we can't do anything about it). Only patch I can suggest for now is to use the Spotify Web Player sigh.

**Comment by aadibajpai** [comment]
@bartekpacia ok @MatejMecka says it's working again with the latest update. Can you confirm?

**Comment by aadibajpai** [comment]
Chris confirms it as well, so I'm closing this now and if it persists, feel free to reopen it.

**Comment by aadibajpai** [comment]
> <img alt="Screenshot 2020-06-03 at 7 24 45 PM" width="814" src="https://user-images.githubusercontent.com/40357511/83668299-00988e80-a5d0-11ea-88aa-19c57314fce6.png">
> 
> Sometimes works, sometimes not quite

That's actually a different thing related to Genius A/B testing. It's fixed on master I just need to make a release.

**Comment by aadibajpai** [comment]
> <img alt="Screenshot 2020-06-03 at 7 24 45 PM" width="814" src="https://user-images.githubusercontent.com/40357511/83668299-00988e80-a5d0-11ea-88aa-19c57314fce6.png">
> 
> Sometimes works, sometimes not quite

new release out, can you test after updating to v1.2.0?

**Comment by bartekpacia** [comment]
<img width="786" alt="Screenshot 2020-06-04 at 3 32 11 PM" src="https://user-images.githubusercontent.com/40357511/83763091-9f78c580-a678-11ea-88df-5ebbae98c3f4.png">
Works fine after upgrading to `v1.2.0`, thank you for this fix :D
