### ISSUE TITLE
Reads window titles from wrong window

### ISSUE THREAD

**Issue by exengo** [SwagLyrics/SwSpotify#30]
With certain programs running at the same time as Spotify, in my case Jetbrains Toolbox but I'm sure this applies to other embedded browser applications, SwSpotify will read the title from the wrong window and report the song name as eg. Jetbrains Toolbox.

This happened on Windows 10 20H2 with Python 3.9.5, SwSpotify 1.2.1 and Jetbrains Toolbox App 1.20.8352.

Closing Jetbrains Toolbox fixes the problem.

**Comment by aadibajpai** [comment]
yeah this is an issue that happens with this specific application (Jetbrains Toolbox), I want to figure out how to go for just spotify

**Comment by aadibajpai** [comment]
@exengo hey there! I know it's been a long time but we just merged #42 that fixes this. If you can, would you like to test out SwSpotify from the current master to confirm if that fixes the issue for you as well so we can then make a release?

**Comment by aadibajpai** [comment]
fixed in v1.2.3
