### ISSUE TITLE
Using pydbus instead of python-dbus

### ISSUE THREAD

**Issue by marioortizmanero** [SwagLyrics/SwSpotify#6]
I wanted to suggest using [pydbus](https://github.com/LEW21/pydbus) instead of python-dbus. The former is much more pythonic (modern), easy to use, and many users are migrating to it. I've used it myself in my project and it's really easy to use coming from python-dbus. I can help you with it myself and do a PR if you want.

**Comment by aadibajpai** [comment]
I'd be happy to move to it but I don't really know how different it is and what's the benefit of using it. If you can tell me what's better in it then I see no problem in upgrading to it!

**Comment by marioortizmanero** [comment]
First off python-dbus is a legacy API and uses a deprecated library called dbus-glib. Pydbus is much more modern and easy to use, here's an example of a module migrating to it, which should explain It better than me: https://github.com/lvht/btk/issues/10. The only bad part is that it doesn't support asynchronous calls but this project doesn't use them anyway. What do you think?

**Comment by aadibajpai** [comment]
> First off python-dbus is a legacy API and uses a deprecated library called dbus-glib. Pydbus is much more modern and easy to use, here's an example of a module migrating to it, which should explain It better than me: [lvht/btk#10](https://github.com/lvht/btk/issues/10). The only downside here that it doesn't support asynchronous calls but this project doesn't use them anyway.
> 
> What do you think? Is it worth it?

Alright, go ahead. Even if there's no such major visible advantage, I guess it's good to use something that's maintained instead of legacy codebase. 

iirc we're using python-dbus since it's pre-installed on linux but let's upgrade lol

**Comment by marioortizmanero** [comment]
Also, another important thing is that pydbus uses the LGPL so this project would have to use it too. Are you OK with that?

**Comment by aadibajpai** [comment]
> Also, another important thing is that pydbus uses the LGPL so this project would have to use it too. Are you OK with that?

I don't think we'd need to modify our license since we're not including the source files of pydbus here, are we? Is it not pip installable or something?

https://softwareengineering.stackexchange.com/questions/141847/how-does-using-a-lgpl-gem-affect-my-mit-licensed-application

**Comment by aadibajpai** [comment]
Also from https://choosealicense.com/licenses/lgpl-3.0/

> However, a larger work using the licensed work through interfaces provided by the licensed work may be distributed under different terms and without source code for the larger work.

**Comment by marioortizmanero** [comment]
Ah okay, I didn't know that. I'll start working on this on a future version then.

**Comment by aadibajpai** [comment]
> Ah okay, I didn't know that. I'll start working on this on a future version then.

Sounds great!

**Comment by marioortizmanero** [comment]
Update on this: it seems that the pydbus maintainer hasn't updated the module in 2 years. There's a discussion about forks and such inside the repo, so it'd be best to implement this once things are more settled.

**Comment by aadibajpai** [comment]
Alright, I see

**Comment by cdosborn** [comment]
FWIW, I'm on debian buster. When I went to install `swaglyrics` I received an import module error for `dbus`. I had to install dbus-python manually. I don't believe it's installed by default any more.

**Comment by aadibajpai** [comment]
> FWIW, I'm on debian buster. When I went to install `swaglyrics` I received an import module error for `dbus`. I had to install dbus-python manually. I don't believe it's installed by default any more.

yes, I had checked the standard preinstalled packages on linux and dbus came preinstalled. That's how it works in the CI too. If you're sure it wasn't preinstalled, can you tell me how you installed it so we might put in a check or something for cases where it's not installed already.

**Comment by cdosborn** [comment]
@aadibajpai the import error was due to my use of a non default python install

**Comment by aadibajpai** [comment]
closing bc current way seems functional
